# Generated by Django 3.1.2 on 2020-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Verify',
        ),
    ]
