# Generated by Django 3.1.2 on 2020-10-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0002_auto_20201016_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify_f',
            name='verification_code',
            field=models.CharField(max_length=30),
        ),
    ]
