# Generated by Django 3.1.2 on 2020-10-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fracture_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fracture_name', models.CharField(max_length=250)),
                ('fracture_file', models.FileField(upload_to='images/flurosis_Detection')),
                ('fracture_image', models.ImageField(upload_to='')),
                ('date_uploaded_fracture', models.DateField(auto_now=True)),
            ],
        ),
    ]
