# Generated by Django 3.1.2 on 2020-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooth_fracture_generator', '0002_auto_20201016_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.CharField(default='file', max_length=255),
            preserve_default=False,
        ),
    ]
