# Generated by Django 3.1.2 on 2020-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooth_fracture_generator', '0003_document_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
